### ISSUE TITLE
OpenMP test?

### ISSUE THREAD

**Issue by rwhetten** [insilico/reliefseq#1]
I compiled and installed ReliefSeq on an Ubuntu 12.04 system that has Boost and OpenMPI libraries installed. The program ran successfully using the --dge-counts-data option as outlined on the web page (http://insilico.utulsa.edu/ReliefSeq.php), although the screen output said it would use 24 threads and the 'top' command showed only one processor used by the reliefseq process. When I try using a PLINK-covariate-file-format input file with the -n option, and a phenotype file specified by the -a option, the program output again says the program will use all 24 available cores, but hangs and does nothing for hours. Is there a way to test the program to make sure it compiled correctly to give access to the openmpi libraries?

**Comment by hexhead** [comment]
I just tried to re-compile my version, and I noticed the "-fopenmp" flag
was not being included (weird), thus OpenMP pragmas were ignored. I just
pushed a new version of Makefile.am to github that includes this flag
specifically. You can pull the latest from github and re-compile:

$ ./bootstrap.sh
$ ./configure
$ make

Hopefully this will get it going.

NOTE: I use the -n/-a options for data files (PLINK), since the "dge" stuff
was an additional for a specific collaborator's file formats, though it
should work fine.

On Sat, Jul 25, 2015 at 9:18 PM, rwhetten notifications@github.com wrote:

> I compiled and installed ReliefSeq on an Ubuntu 12.04 system that has
> Boost and OpenMPI libraries installed. The program ran successfully using
> the --dge-counts-data option as outlined on the web page (
> http://insilico.utulsa.edu/ReliefSeq.php), although the screen output
> said it would use 24 threads and the 'top' command showed only one
> processor used by the reliefseq process. When I try using a
> PLINK-covariate-file-format input file with the -n option, and a phenotype
> file specified by the -a option, the program output again says the program
> will use all 24 available cores, but hangs and does nothing for hours. Is
> there a way to test the program to make sure it compiled correctly to give
> access to the openmpi libraries?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/insilico/reliefseq/issues/1.

## 

Bill C. White, MS
Research Associate Programmer
University of Tulsa
Tandy School of Computer Science
http://insilico.utulsa.edu/

**Comment by rwhetten** [comment]
Thanks for the quick reply! I pulled the new version and re-compiled, and did see a difference in that the warnings I saw in the first compiler run (shown below) were no longer present.
Dataset.cpp:2582:0: warning: ignoring #pragma omp for [-Wunknown-pragmas]
Dataset.cpp:3059:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
Dataset.cpp:3134:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]

However, the program still hangs, apparently at the step of starting the OpenMP threads. The last few lines of output are:
20150726 - 08:52:39 - 24 OpenMP processors available
20150726 - 08:52:39 - 1 OpenMP threads in work team
20150726 - 08:52:39 - RReliefF initialization
20150726 - 08:52:39 - ReliefSeq will remove 0 attributes on first iteration
20150726 - 08:52:39 - ReliefSeq is removing attributes until best 29889 remain
20150726 - 08:52:39 - 24 OpenMP processors available
20150726 - 08:52:39 - ReliefSeq will use 24 threads

At this point 'top' shows 100% use of one CPU but 0.0% RAM use, and nothing more happens.
Is there a way to confirm that my gcc installation includes OpenMP? The only thing I see in the output from the ./configure script that seems relevant is
checking for omp_get_num_threads in -lgomp... yes

**Comment by rwhetten** [comment]
I confirmed that my Ubuntu system has gcc-4.6 with libgomp1 installed, so it should have OpenMP capability. Setting OMP_NUM_THREADS to 12 has no effect on the output from ReliefSeq, though - it still says "ReliefSeq will use 24 threads" before it hangs.

**Comment by hexhead** [comment]
To be honest, I haven't tested much with quantitative phenotype/class (the
Regression Relief-F part of reliefseq), which it looks like you're running.
If you send me the complete output, and/or if you can send me the data set
(providing there are no privacy issues), I will try and debug it here.

On Sun, Jul 26, 2015 at 8:39 AM, rwhetten notifications@github.com wrote:

> I confirmed that my Ubuntu system has gcc-4.6 with libgomp1 installed, so
> it should have OpenMP capability. Setting OMP_NUM_THREADS to 12 has no
> effect on the output from ReliefSeq, though - it still says "ReliefSeq will
> use 24 threads" before it hangs.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/insilico/reliefseq/issues/1#issuecomment-124988242.

## 

Bill C. White, MS
Research Associate Programmer
University of Tulsa
Tandy School of Computer Science
http://insilico.utulsa.edu/

**Comment by rwhetten** [comment]
I created a small test set of transcripts (85 transcripts) and phenotypes (144 phenotypes); the output to the screen from a run of reliefseq is shown below. The command-line call to reliefseq was
reliefseq -n test.transcripts.txt -a test.pheno.txt -k 0 --kopt-begin 1 --kopt-end 60 --write-each-k-scores -o test.run 
I can provide the test dataset, but Github does not allow attaching a tgz archive to a comment - what is the best way to get it to you?
----------------- begin ReliefSeq screen output ---------------------------
20150726 - 14:16:21 - reliefseq starting
20150726 - 14:16:21 - Processing command line arguments
20150726 - 14:16:21 - Determining analysis type
20150726 - 14:16:21 - Numeric-only analysis requested
20150726 - 14:16:21 - Checking for numeric data and/or alternate phenotype files
20150726 - 14:16:21 - Loading individual IDs from numeric data file: test.transcripts.txt
20150726 - 14:16:21 - 144 numeric IDs read
20150726 - 14:16:21 - Loading individual IDs from alternate phenotype file: test.pheno.txt
20150726 - 14:16:21 - 144 non-missing phenotype IDs read
20150726 - 14:16:21 - Determining the IDs to be read from the dataset
20150726 - 14:16:21 - IDs come from the numeric and the alternate phenotype files. Checking for intersection/matches
20150726 - 14:16:21 - 144 individual IDs read from numeric and/or phenotype file(s)
20150726 - 14:16:21 - Loading and preparing data for Reliefseq analysis
20150726 - 14:16:21 - Reading numeric data set
20150726 - 14:16:21 - Default SNP diff metric: gm
20150726 - 14:16:21 - Default SNP nearest neighbors distance metric: gm
20150726 - 14:16:21 - Default continuous distance metric: manhattan
20150726 - 14:16:21 - Reading numerics from test.transcripts.txt
20150726 - 14:16:21 - Read 85 numeric attributes
20150726 - 14:16:21 - Detecting class type from file: test.pheno.txt
20150726 - 14:16:21 - Continuous phenotypes detected
20150726 - 14:16:21 - Reading alternate phenotypes from test.pheno.txt... 
20150726 - 14:16:21 - Updating all level counts:
20150726 - 14:16:21 - 100/144
20150726 - 14:16:21 - 144/144 done
20150726 - 14:16:21 - Excluding monomorphic SNPs
20150726 - 14:16:21 - 0 SNPs excluded as monomorphic
20150726 - 14:16:21 - Read 144 phenotypes. 144 instances in the data set
20150726 - 14:16:21 - New SNP distance diff metric: gm 0x41f5f0
20150726 - 14:16:21 - New SNP distance nearest neighbor metric: gm 0x41f5f0
20150726 - 14:16:21 - New continuous distance metric: manhattan 0x41f7e0
20150726 - 14:16:21 - Dataset has:
20150726 - 14:16:21 - instances:      144
20150726 - 14:16:21 - numerics:       85
20150726 - 14:16:21 - continuous phenotype, min: 91.5, max: 145.7
20150726 - 14:16:21 - total elements: 12384
20150726 - 14:16:21 - 0 missing attribute values detected
20150726 - 14:16:21 - Total genotyping rate: -nan
20150726 - 14:16:21 - 0 missing numeric values detected
20150726 - 14:16:21 - Running ReliefSeq
20150726 - 14:16:21 - ReliefSeq controller initialization:
20150726 - 14:16:21 - Constructing Regression ReliefF...
20150726 - 14:16:21 - ReliefF initialization with boost command line parameters:
20150726 - 14:16:21 - k nearest neighbors will be optimized
20150726 - 14:16:21 - Scores will not be normalized
20150726 - 14:16:21 - Number of samples: m = 144
20150726 - 14:16:21 - Sampling all instances deterministically
20150726 - 14:16:21 - ReliefF SNP weight update metric: gm
20150726 - 14:16:21 - ReliefF continuous distance weight update metric: manhattan
20150726 - 14:16:21 - Weight by distance method: equal
20150726 - 14:16:21 - 24 OpenMP processors available
20150726 - 14:16:21 - 1 OpenMP threads in work team
20150726 - 14:16:21 - RReliefF initialization
20150726 - 14:16:21 - ReliefSeq will remove 0 attributes on first iteration
20150726 - 14:16:21 - ReliefSeq is removing attributes until best 85 remain
20150726 - 14:16:21 - 24 OpenMP processors available
20150726 - 14:16:21 - ReliefSeq will use 24 threads
---------------------------- end output; program hangs here - killed with Ctrl-C ------------------------

**Comment by hexhead** [comment]
Thanks for the details. You can send a tarball to bill dot c dot white at gmail.

**Comment by hexhead** [comment]
If you take out the -k and -kopt params, does it run okay? I think I have duplicated the error you are experiencing, since it seems to run okay without these params. reliefseq -n test.transcripts.txt -a test.pheno.txt -o test.run

**Comment by hexhead** [comment]
Hmm, it's working with a case-control phenotype and the kopt params. Must be something about the quantitative phenotype.

**Comment by rwhetten** [comment]
The most recent version pulled from github worked with continuous phenotypic data for 144 individuals and transcript read counts for 29,000 transcripts, and completed analysis in about 25 minutes using 3 to 7 cores (per the 'top' command). The program is very memory-efficient - RAM usage stayed at 0.0% on the 'top' display for the entire job. The -k and -kopt options seemed to work fine. Thanks for the quick fix - great job with the program!

**Comment by hexhead** [comment]
Excellent! It's so hard to test all the options when I do this work for research projects and then quickly move on to other things. It's good to have people like you to initiate and test various use cases.
